### ISSUE TITLE
Data packet needs FreshnessPeriod

### ISSUE THREAD

**Issue by yoursunny** [chavoosh/ndn-mongo-fileserver#1]
Currently, the chunker generates Data without FreshnessPeriod element:
https://github.com/chavoosh/ndn-mongo-fileserver/blob/945e2b16bda54b0392d377fd9658921beecaf7ec/src/util/chunker.cpp#L236-L238

According to NDN Packet Format 0.3:
* An Interest with MustBeFresh element cannot be satisfied by non-fresh Data.
* A Data without FreshnessPeriod is immediately non-fresh.

When frontend sends a version discovery Interest CanBePrefix+MustBeFresh to discover version, a Data generated by the chunker would not be able to satisfy that Interest.

Note: this bug was discovered during my testing of NDNts `@ndn/cat` package, which implements NDN Packet Format 0.3 semantics.

**Comment by chavoosh** [comment]
`chunker` tool generates Data packets with `10s` freshness period. 
Commit: https://github.com/chavoosh/ndn-mongo-fileserver/commit/edf5602c77f6703bbda7ae2fdad30e464b86379f
