### ISSUE TITLE
Add session-segments.py script

### ISSUE THREAD

**Issue by wenkaizheng** [chavoosh/ndn-mongo-fileserver#7]
This script plots the number of received Data packets by the consumer, during each video session.

**Comment by chavoosh** [comment]
I would change the title to this:
`Add session-segment.py script`

This script does not exist in the repo, so you cannot talk about a bug in it, yet.
First, explain what this script does and that is it.
Then in another comment talk about the bug in your code and the way you are trying to solve it.

**Comment by chavoosh** [comment]
Also, assign this issue to yourself.

**Comment by wenkaizheng** [comment]
The max segments show from sort command line is 165538. Second max and Third max segment are 156024 and 155081.  So this plot may be right? The top 3 sessions from plot are around 160000.
Do you think this plot still have problem ?

![image](https://user-images.githubusercontent.com/31551859/74692091-f5496080-51a2-11ea-9548-892b6b50a357.png)

**Comment by chavoosh** [comment]
Please share the log file and the session ID with the max number of segments.

**Comment by wenkaizheng** [comment]
Session ID is 355326784144
The name of log file is segment-stats.log, but this file is to big to load in here.  I can share this file with you through Slack.

**Comment by chavoosh** [comment]
I checked the log file and I confirm your observation. Session ID `355326784144` is a long video with too many segments.
Do you need to do more tests to validate the implementation?

**Comment by wenkaizheng** [comment]
I tested it yesterday and also today morning.  I think i can push my code today.

**Comment by wenkaizheng** [comment]
I will take a look at other sessions for testing as well, and i will be able to push my code today.
